package com.rnj.ddangily.model;

import java.util.Date;

public class Instagram {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instagram.instagram_id
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    private Long instagramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instagram.id
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instagram.media_type
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    private String mediaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instagram.media_url
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    private String mediaUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instagram.permalink
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    private String permalink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instagram.username
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instagram.caption
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    private String caption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instagram.collection_time
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    private Date collectionTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instagram.instagram_id
     *
     * @return the value of instagram.instagram_id
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    public Long getInstagramId() {
        return instagramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instagram.instagram_id
     *
     * @param instagramId the value for instagram.instagram_id
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    public void setInstagramId(Long instagramId) {
        this.instagramId = instagramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instagram.id
     *
     * @return the value of instagram.id
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instagram.id
     *
     * @param id the value for instagram.id
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instagram.media_type
     *
     * @return the value of instagram.media_type
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    public String getMediaType() {
        return mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instagram.media_type
     *
     * @param mediaType the value for instagram.media_type
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    public void setMediaType(String mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instagram.media_url
     *
     * @return the value of instagram.media_url
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    public String getMediaUrl() {
        return mediaUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instagram.media_url
     *
     * @param mediaUrl the value for instagram.media_url
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    public void setMediaUrl(String mediaUrl) {
        this.mediaUrl = mediaUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instagram.permalink
     *
     * @return the value of instagram.permalink
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    public String getPermalink() {
        return permalink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instagram.permalink
     *
     * @param permalink the value for instagram.permalink
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    public void setPermalink(String permalink) {
        this.permalink = permalink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instagram.username
     *
     * @return the value of instagram.username
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instagram.username
     *
     * @param username the value for instagram.username
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instagram.caption
     *
     * @return the value of instagram.caption
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    public String getCaption() {
        return caption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instagram.caption
     *
     * @param caption the value for instagram.caption
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    public void setCaption(String caption) {
        this.caption = caption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instagram.collection_time
     *
     * @return the value of instagram.collection_time
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    public Date getCollectionTime() {
        return collectionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instagram.collection_time
     *
     * @param collectionTime the value for instagram.collection_time
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    public void setCollectionTime(Date collectionTime) {
        this.collectionTime = collectionTime;
    }
}