server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


---
#spring:
#  config:
#    activate:
#      on-profile: "local"
#  datasource:
#    url: jdbc:log4jdbc:mariadb
#    driver-class-name: "net.sf.log4jdbc.DriverSpy"
#    username: "ddangily_admin"
#    password: "root1234"



#spring:
#  config:
#    activate:
#      on-profile: @spring.profiles.active@
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:log4jdbc:mariadb://@db.url@:@db.port@
#    username: @db.user@
#    password: @db.password@

