server:
  port: 8080

spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  profiles:
    active: @spring.profiles.active@

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://@db.url@:@db.port@/@db.name@
    username: @db.user@
    password: @db.password@

#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp


---
