package com.rnj.ddangily.persistence;

import com.rnj.ddangily.model.Instagram;
import java.util.List;

public interface InstagramMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instagram
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    int deleteByPrimaryKey(Long instagramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instagram
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    int insert(Instagram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instagram
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    Instagram selectByPrimaryKey(Long instagramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instagram
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    List<Instagram> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instagram
     *
     * @mbg.generated Sat Aug 28 18:10:53 KST 2021
     */
    int updateByPrimaryKey(Instagram record);
}